### ISSUE TITLE
deactivate sub dimensions

### ISSUE THREAD

**Issue by hulsbosch** [Blocss/dimensions#1]
Would like to see an option to deactivate certain dimensions. E.g. the option to put 12 in the width-divisions but not compile all .u-x-12 classes. For example activate the '5' and/ or deactivate the '11' sub dimension when I want to use .u-5-12 but don't need .u-11-12.

**Comment by bramsmulders** [comment]
This will be to obscure for future developers, they see the classes in markup and expect it to work. Please use tools like uncss for the purpose of unused classes.
